using Ambev.DeveloperEvaluation.Domain.Events;
using Ambev.DeveloperEvaluation.Domain.Exceptions;
using Ambev.DeveloperEvaluation.Domain.Services;
using Ambev.DeveloperEvaluation.Domain.ValueObjects;

namespace Ambev.DeveloperEvaluation.Domain.Entities;

public sealed class Sale
{
    public const int SaleNumberMaximumLength = 50;
    public const int MaximumItems = 100;
    public static readonly TimeSpan MaximumFutureTolerance = TimeSpan.FromMinutes(5);

    private readonly List<SaleItem> _items = [];
    private readonly List<SaleDomainEvent> _domainEvents = [];

    public Guid Id { get; private set; }
    public string SaleNumber { get; private set; } = string.Empty;
    public DateTimeOffset SaleDate { get; private set; }
    public ExternalIdentity Customer { get; private set; } = null!;
    public ExternalIdentity Branch { get; private set; } = null!;
    public IReadOnlyList<SaleItem> Items => _items.AsReadOnly();
    public decimal TotalAmount { get; private set; }
    public bool IsCancelled { get; private set; }
    public DateTimeOffset? CancelledAt { get; private set; }
    public bool IsDeleted { get; private set; }
    public DateTimeOffset? DeletedAt { get; private set; }
    public DateTimeOffset CreatedAt { get; private set; }
    public DateTimeOffset UpdatedAt { get; private set; }
    public long Version { get; private set; }
    public IReadOnlyList<SaleDomainEvent> DomainEvents => _domainEvents.AsReadOnly();

    private Sale()
    {
    }

    public static Sale Create(
        string? saleNumber,
        DateTimeOffset saleDate,
        ExternalIdentity? customer,
        ExternalIdentity? branch,
        IEnumerable<SaleItemDraft?>? items,
        DateTimeOffset now)
    {
        var normalizedNumber = NormalizeSaleNumber(saleNumber);
        var normalizedNow = now.ToUniversalTime();
        var normalizedSaleDate = ValidateSaleDate(saleDate, normalizedNow);
        var validatedCustomer = RequireIdentity(customer, RequiredIdentity.Customer);
        var validatedBranch = RequireIdentity(branch, RequiredIdentity.Branch);
        var drafts = MaterializeDrafts(items);

        if (drafts.Any(item => item.Id.HasValue))
            throw new DomainValidationException(
                DomainErrorCodes.SaleItem.IdNotAllowedOnCreate,
                "Item IDs are generated by the server when a sale is created.");

        ValidateUniqueProducts(drafts);

        var sale = new Sale
        {
            Id = Guid.NewGuid(),
            SaleNumber = normalizedNumber,
            SaleDate = normalizedSaleDate,
            Customer = validatedCustomer,
            Branch = validatedBranch,
            CreatedAt = normalizedNow,
            UpdatedAt = normalizedNow,
            Version = 1
        };

        foreach (var draft in drafts)
        {
            sale._items.Add(SaleItem.Create(
                sale.Id,
                RequireProduct(draft.Product),
                draft.Quantity,
                draft.UnitPrice));
        }

        sale.RecalculateTotal();
        sale._domainEvents.Add(new SaleCreatedEvent(sale.Id, sale.Version, normalizedNow));
        return sale;
    }

    public bool Update(
        DateTimeOffset saleDate,
        ExternalIdentity? customer,
        ExternalIdentity? branch,
        IEnumerable<SaleItemDraft?>? activeItems,
        DateTimeOffset now)
    {
        EnsureCanUpdate();
        var normalizedNow = ValidateOperationTime(now);
        var plan = BuildUpdatePlan(saleDate, customer, branch, activeItems, normalizedNow);

        if (!HasChanges(plan))
            return false;

        ApplyUpdate(plan, normalizedNow);
        return true;
    }

    public bool CancelItem(Guid itemId, DateTimeOffset now)
    {
        EnsureAvailable();

        var item = _items.SingleOrDefault(candidate => candidate.Id == itemId)
                   ?? throw new DomainNotFoundException(
                       DomainErrorCodes.SaleItem.NotFound,
                       $"Item '{itemId}' was not found in sale '{Id}'.");

        if (item.IsCancelled)
            return false;

        if (IsCancelled)
            throw new DomainConflictException(
                DomainErrorCodes.Sale.Cancelled,
                "A cancelled sale cannot contain an active item.");

        var normalizedNow = ValidateOperationTime(now);
        item.Cancel(normalizedNow);
        Version++;
        UpdatedAt = normalizedNow;
        RecalculateTotal();
        _domainEvents.Add(new ItemCancelledEvent(Id, item.Id, Version, normalizedNow));

        if (_items.All(candidate => candidate.IsCancelled))
        {
            IsCancelled = true;
            CancelledAt = normalizedNow;
            _domainEvents.Add(new SaleCancelledEvent(Id, Version, normalizedNow));
        }

        return true;
    }

    public bool Cancel(DateTimeOffset now)
    {
        EnsureAvailable();

        if (IsCancelled)
            return false;

        var normalizedNow = ValidateOperationTime(now);

        foreach (var item in _items.Where(item => !item.IsCancelled))
            item.Cancel(normalizedNow);

        IsCancelled = true;
        CancelledAt = normalizedNow;
        TotalAmount = 0m;
        UpdatedAt = normalizedNow;
        Version++;
        _domainEvents.Add(new SaleCancelledEvent(Id, Version, normalizedNow));
        return true;
    }

    public bool Delete(DateTimeOffset now)
    {
        if (IsDeleted)
            return false;

        var normalizedNow = ValidateOperationTime(now);
        IsDeleted = true;
        DeletedAt = normalizedNow;
        UpdatedAt = normalizedNow;
        Version++;
        return true;
    }

    public void ClearDomainEvents()
    {
        _domainEvents.Clear();
    }

    private void EnsureCanUpdate()
    {
        EnsureAvailable();

        if (IsCancelled)
            throw new DomainConflictException(
                DomainErrorCodes.Sale.Cancelled,
                "A cancelled sale cannot be updated.");
    }

    private SaleUpdatePlan BuildUpdatePlan(
        DateTimeOffset saleDate,
        ExternalIdentity? customer,
        ExternalIdentity? branch,
        IEnumerable<SaleItemDraft?>? activeItems,
        DateTimeOffset now)
    {
        var normalizedSaleDate = ValidateSaleDate(saleDate, now);
        var validatedCustomer = RequireIdentity(customer, RequiredIdentity.Customer);
        var validatedBranch = RequireIdentity(branch, RequiredIdentity.Branch);
        var drafts = MaterializeDrafts(activeItems);
        var cancelledItems = _items.Where(item => item.IsCancelled).ToArray();

        EnsureItemCapacity(drafts.Count, cancelledItems.Length);

        return new SaleUpdatePlan(
            normalizedSaleDate,
            validatedCustomer,
            validatedBranch,
            BuildItemUpdatePlans(drafts, cancelledItems));
    }

    private List<ItemUpdatePlan> BuildItemUpdatePlans(
        IReadOnlyCollection<SaleItemDraft> drafts,
        IReadOnlyCollection<SaleItem> cancelledItems)
    {
        var products = new HashSet<string>(
            cancelledItems.Select(item => item.Product.ExternalId),
            StringComparer.Ordinal);
        var existingById = _items.ToDictionary(item => item.Id);
        var includedExistingIds = new HashSet<Guid>();
        var plans = new List<ItemUpdatePlan>(drafts.Count);

        foreach (var draft in drafts)
        {
            var product = RequireProduct(draft.Product);
            _ = SaleDiscountPolicy.Calculate(draft.Quantity, draft.UnitPrice);

            if (!products.Add(product.ExternalId))
                throw DuplicateProduct(product.ExternalId);

            plans.Add(BuildItemUpdatePlan(draft, product, existingById, includedExistingIds));
        }

        EnsureEveryActiveItemIsIncluded(includedExistingIds);
        return plans;
    }

    private static ItemUpdatePlan BuildItemUpdatePlan(
        SaleItemDraft draft,
        ExternalIdentity product,
        IReadOnlyDictionary<Guid, SaleItem> existingById,
        ISet<Guid> includedExistingIds)
    {
        if (!draft.Id.HasValue)
            return new ItemUpdatePlan(null, draft);

        if (draft.Id.Value == Guid.Empty ||
            !existingById.TryGetValue(draft.Id.Value, out var existing) ||
            existing.IsCancelled)
        {
            throw new DomainValidationException(
                DomainErrorCodes.SaleItem.InvalidId,
                $"Item '{draft.Id}' is not an active item of this sale.");
        }

        if (!includedExistingIds.Add(existing.Id))
            throw new DomainValidationException(
                DomainErrorCodes.SaleItem.DuplicateId,
                $"Item '{existing.Id}' appears more than once.");

        if (existing.Product != product)
            throw new DomainValidationException(
                DomainErrorCodes.SaleItem.ProductIsImmutable,
                "The product identity and snapshot of an existing item cannot be changed.");

        return new ItemUpdatePlan(existing, draft);
    }

    private void EnsureEveryActiveItemIsIncluded(ISet<Guid> includedExistingIds)
    {
        if (_items.Any(item => !item.IsCancelled && !includedExistingIds.Contains(item.Id)))
            throw new DomainValidationException(
                DomainErrorCodes.SaleItem.ActiveItemOmitted,
                "Every active item must be included in an update. Use the cancellation endpoint to remove one.");
    }

    private static void EnsureItemCapacity(int activeItemCount, int cancelledItemCount)
    {
        if (activeItemCount + cancelledItemCount > MaximumItems)
            throw new DomainValidationException(
                DomainErrorCodes.Sale.TooManyItems,
                $"A sale can contain at most {MaximumItems} items, including cancelled items.");
    }

    private bool HasChanges(SaleUpdatePlan plan)
    {
        return SaleDate != plan.SaleDate ||
               Customer != plan.Customer ||
               Branch != plan.Branch ||
               plan.Items.Any(item => item.Existing is null ||
                                      item.Existing.Quantity != item.Draft.Quantity ||
                                      item.Existing.UnitPrice != item.Draft.UnitPrice);
    }

    private void ApplyUpdate(SaleUpdatePlan plan, DateTimeOffset now)
    {
        SaleDate = plan.SaleDate;
        Customer = plan.Customer;
        Branch = plan.Branch;

        foreach (var item in plan.Items)
            ApplyItemUpdate(item);

        UpdatedAt = now;
        Version++;
        RecalculateTotal();
        _domainEvents.Add(new SaleModifiedEvent(Id, Version, now));
    }

    private void ApplyItemUpdate(ItemUpdatePlan plan)
    {
        if (plan.Existing is not null)
        {
            plan.Existing.Update(plan.Draft.Quantity, plan.Draft.UnitPrice);
            return;
        }

        _items.Add(SaleItem.Create(
            Id,
            plan.Draft.Product,
            plan.Draft.Quantity,
            plan.Draft.UnitPrice));
    }

    private static string NormalizeSaleNumber(string? saleNumber)
    {
        if (string.IsNullOrWhiteSpace(saleNumber))
            throw new DomainValidationException(DomainErrorCodes.Sale.NumberRequired, "Sale number is required.");

        var normalized = saleNumber.Trim().ToUpperInvariant();

        if (normalized.Length > SaleNumberMaximumLength)
            throw new DomainValidationException(
                DomainErrorCodes.Sale.NumberTooLong,
                $"Sale number must contain at most {SaleNumberMaximumLength} characters.");

        if (normalized.Any(char.IsControl))
            throw new DomainValidationException(
                DomainErrorCodes.Sale.NumberContainsControlCharacter,
                "Sale number cannot contain control characters.");

        return normalized;
    }

    private static DateTimeOffset ValidateSaleDate(DateTimeOffset saleDate, DateTimeOffset now)
    {
        var normalized = saleDate.ToUniversalTime();

        if (normalized > now.Add(MaximumFutureTolerance))
            throw new DomainValidationException(
                DomainErrorCodes.Sale.DateTooFarInFuture,
                "Sale date cannot be more than five minutes in the future.");

        return normalized;
    }

    private static ExternalIdentity RequireIdentity(
        ExternalIdentity? identity,
        RequiredIdentity requiredIdentity)
    {
        if (identity is not null)
            return identity;

        var (code, message) = requiredIdentity switch
        {
            RequiredIdentity.Customer => (DomainErrorCodes.Sale.CustomerRequired, "Customer is required."),
            RequiredIdentity.Branch => (DomainErrorCodes.Sale.BranchRequired, "Branch is required."),
            RequiredIdentity.Product => (DomainErrorCodes.SaleItem.ProductRequired, "Product is required."),
            _ => throw new ArgumentOutOfRangeException(nameof(requiredIdentity), requiredIdentity, null)
        };

        throw new DomainValidationException(code, message);
    }

    private static ExternalIdentity RequireProduct(ExternalIdentity? product)
    {
        return RequireIdentity(product, RequiredIdentity.Product);
    }

    private enum RequiredIdentity
    {
        Customer,
        Branch,
        Product
    }

    private static List<SaleItemDraft> MaterializeDrafts(IEnumerable<SaleItemDraft?>? items)
    {
        if (items is null)
            throw new DomainValidationException(DomainErrorCodes.Sale.ItemsRequired, "At least one item is required.");

        var drafts = items.ToList();

        if (drafts.Count == 0)
            throw new DomainValidationException(DomainErrorCodes.Sale.ItemsRequired, "At least one item is required.");

        if (drafts.Count > MaximumItems)
            throw new DomainValidationException(
                DomainErrorCodes.Sale.TooManyItems,
                $"A sale can contain at most {MaximumItems} items.");

        if (drafts.Any(item => item is null))
            throw new DomainValidationException(DomainErrorCodes.SaleItem.NullItem, "Sale items cannot be null.");

        return drafts.Select(item => item!).ToList();
    }

    private static void ValidateUniqueProducts(IEnumerable<SaleItemDraft> drafts)
    {
        var products = new HashSet<string>(StringComparer.Ordinal);

        foreach (var draft in drafts)
        {
            var product = RequireProduct(draft.Product);
            SaleDiscountPolicy.Calculate(draft.Quantity, draft.UnitPrice);

            if (!products.Add(product.ExternalId))
                throw DuplicateProduct(product.ExternalId);
        }
    }

    private static DomainValidationException DuplicateProduct(string externalId)
    {
        return new DomainValidationException(
            DomainErrorCodes.SaleItem.DuplicateProduct,
            $"Product '{externalId}' appears more than once in the sale.");
    }

    private DateTimeOffset ValidateOperationTime(DateTimeOffset now)
    {
        var normalized = now.ToUniversalTime();

        if (normalized < CreatedAt)
            throw new DomainValidationException(
                DomainErrorCodes.Sale.OperationBeforeCreation,
                "Operation time cannot be earlier than sale creation time.");

        return normalized;
    }

    private void EnsureAvailable()
    {
        if (IsDeleted)
            throw new DomainConflictException(DomainErrorCodes.Sale.Deleted, "A deleted sale cannot be changed.");
    }

    private void RecalculateTotal()
    {
        TotalAmount = _items.Sum(item => item.EffectiveAmount);
    }

    private sealed record SaleUpdatePlan(
        DateTimeOffset SaleDate,
        ExternalIdentity Customer,
        ExternalIdentity Branch,
        IReadOnlyList<ItemUpdatePlan> Items);

    private sealed record ItemUpdatePlan(SaleItem? Existing, SaleItemDraft Draft);
}
